lib/pegelclub_ex_web/router.ex
defmodule PegelclubExWeb.Router do
  use PegelclubExWeb, :router

  import PegelclubExWeb.UserAuth
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PegelclubExWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PegelclubExWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/match_live/:id", MatchLive
    live "/control_panel_live/:id", ControlPanelLive

    get "/", PageController, :index
    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show
    resources "/players", PlayerController, only: [:new, :create, :edit, :update, :index]

    resources "/matches", MatchController, only: [:index, :show, :new, :create, :delete] do
      resources "/scores", ScoreController, only: [:new, :create, :edit, :update, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PegelclubExWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PegelclubExWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PegelclubExWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    # get "/users/register", UserRegistrationController, :new
    # post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    # get "/users/reset_password", UserResetPasswordController, :new
    # post "/users/reset_password", UserResetPasswordController, :create
    # get "/users/reset_password/:token", UserResetPasswordController, :edit
    # put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PegelclubExWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users", UserSettingsController, :index
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PegelclubExWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    # get "/users/confirm", UserConfirmationController, :new
    # post "/users/confirm", UserConfirmationController, :create
    # get "/users/confirm/:token", UserConfirmationController, :edit
    # post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/pegelclub_ex/game/match.ex
defmodule PegelclubEx.Game.Match do
  use Ecto.Schema

  import Ecto.Changeset

  alias PegelclubEx.Game.Score

  schema "matches" do
    field :played_at, :date

    has_many :scores, Score, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(match, attrs) do
    match
    |> cast(attrs, [:played_at])
    |> validate_required([:played_at])
    |> unique_constraint([:played_at], message: "Für dieses Datum existiert bereits ein Spiel")
  end
end

lib/pegelclub_ex_web/controllers/match_controller.ex
defmodule PegelclubExWeb.MatchController do
  use PegelclubExWeb, :controller

  alias PegelclubEx.{Game, Repo}
  alias PegelclubEx.Game.{Match}

  def index(conn, _params) do
    matches = Game.list_matches()
    stats = Game.all_match_stats

    render(conn, "index.html", matches: matches, stats: stats)
  end

  def new(conn, _params) do
    changeset = Game.change_match(%Match{}, %{played_at: Date.utc_today})

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"match" => match_params}) do
    case Game.create_match_with_scores(match_params) do
      {:ok, match} ->
        conn
        |> put_flash(:info, "Match created successfully.")
        |> redirect(to: Routes.live_path(conn, PegelclubExWeb.MatchLive, match.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    match = Game.get_match!(id)
      |> Repo.preload(scores: :player)

    render(conn, "show.html",
      match: match,
      scores: Game.match_scores_sorted_by_name(match),
      match_stats: Game.match_stats(match)
    )
  end

  def delete(conn, %{"id" => id}) do
    match = Game.get_match!(id)
    {:ok, _match} = Game.delete_match(match)

    conn
    |> put_flash(:info, "Spielstand erfolgreich gelöscht!")
    |> redirect(to: Routes.match_path(conn, :index))
  end
end

lib/pegelclub_ex_web/live/match_live.ex
defmodule PegelclubExWeb.MatchLive do
  use PegelclubExWeb, :live_view

  alias PegelclubEx.{Game, Repo}

  def mount(%{"id" => id}, _session, socket) do
    if connected?(socket), do: Game.subscribe_to_scores(id)

    match = Game.get_match!(id)
    |> Repo.preload(scores: :player)

    scores = Game.match_scores_sorted_by_name(match)
    stats = Game.match_stats(match)

    {:ok, assign(socket, match: match, scores: scores, match_stats: stats)}
  end

  def handle_info({:score_updated, score}, socket) do
    score = Repo.preload(score, [:player, :match])


    socket = socket
      |> update(:scores, fn scores -> Enum.map(scores, fn s -> if s.id == score.id, do: score, else: s end) end)
      |> update(:match_stats, fn _ -> Game.match_stats(score.match) end)

    {:noreply, socket}
  end

  def handle_info(_, socket), do: {:noreply, socket}
end

lib/pegelclub_ex_web/views/match_view.ex
defmodule PegelclubExWeb.MatchView do
  use PegelclubExWeb, :view

  def player_symbol(score) do
    if score.is_present do
      if score.player.guest do
        "🔹"
      else
        "🟢"
      end
    else
      "🔴"
    end
  end

  def pudel_king_symbol(score, pudel_king_value) do
    if score.penalty_pudel == pudel_king_value do
      "👑"
    else
      ""
    end
  end
end

lib/pegelclub_ex_web/templates/match/form.html.heex
<.form :let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field mt-5">
    <%= label f, "Datum", class: "label" %>
    <div class="control">
      <%= date_input f, :played_at, class: "input" %>
    </div>
    <%= error_tag f, :played_at %>
  </div>

  <div class="is-flex has-gap-3 is-justify-content-end">
    <%= link "Zurück", to: Routes.match_path(@conn, :index), class: "button is-ghost" %>
    <%= submit "Save", class: "button is-primary" %>
  </div>
</.form>

lib/pegelclub_ex_web/templates/match/index.html.heex
<section class="hero is-primary is-small">
  <div class="hero-body">
    <p class="title">
      Übersicht
    </p>
  </div>
</section>

<section class="content-container pt-4">

  <div class="is-flex is-justify-content-center has-gap-6">
    <%= link "Neues Spiel", to: Routes.match_path(@conn, :new), class: "button is-primary" %>
  </div>

  <div class="table-container mt-6">
    <table class="table is-striped mx-auto">
      <thead>
        <tr>
          <th class="is-white-space-nowrap">Datum</th>
          <th class="is-white-space-nowrap">Einnahmen</th>
          <th class="is-white-space-nowrap">Durchschnitt</th>
          <th class="is-white-space-nowrap">Pudelkönig:in</th>
          <th class="is-white-space-nowrap">Bezahlt</th>
        </tr>
      </thead>
      <tbody>
    <%= for match <- @matches do %>
      <tr>
        <td class="is-white-space-nowrap">
          <%= link date_format(match.played_at), to: Routes.live_path(@conn, PegelclubExWeb.MatchLive, match.id) %>
        </td>
        <td class="has-text-right is-white-space-nowrap"><%= currency_format(@stats[match.id][:total] + @stats[match.id][:penalties_not_present]) %></td>
        <td class="has-text-right is-white-space-nowrap"><%= currency_format @stats[match.id][:average] %></td>
        <td class="has-text-right is-white-space-nowrap"><%= @stats[match.id][:pudel_king_value] %></td>
        <td class="has-text-right is-white-space-nowrap">
          <%= PegelclubEx.Game.match_scores_sorted_by_name(match) |> Enum.filter(fn score -> score.has_payed end) |> Enum.count %>
          /
          <%= PegelclubEx.Game.match_scores_sorted_by_name(match) |> Enum.count %>
        </td>
      </tr>
    <% end %>
      </tbody>
    </table>
  </div>
</section>

lib/pegelclub_ex_web/templates/match/new.html.heex
<section class="content-container pt-4">
  <h1 class="title">Neues Spiel</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.match_path(@conn, :create)) %>
</section>

lib/pegelclub_ex_web/templates/match/show.html.heex
<h1 class="is-size-3">Match vom <%= @match.played_at %></h1>

<section class="level is-mobile mt-6">
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Gesamt</p>
      <p class="title"><%= currency_format Map.get(@match_stats, :total) %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Durchschnitt</p>
      <p class="title"><%= currency_format Map.get(@match_stats, :average) %></p>
    </div>
  </div>
</section>
<section class="level is-mobile">
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Mitspieler</p>
      <p class="title"><%= Enum.count(@scores) %></p>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <p class="heading">Abwesend</p>
      <p class="title"><%= Enum.count(@scores, fn s -> !s.is_present end) %></p>
    </div>
  </div>
</section>

<div class="is-flex is-justify-content-center has-gap-5">
  <%= link "Gast hinzufügen", to: Routes.match_score_path(@conn, :new, @match), class: "button is-rounded" %>

  <label class="checkbox">
    <input type="checkbox" id="toggle-hidable-cols" checked>
    Strafen anzeigen
  </label>
</div>

<div class="table-container mt-6">
  <table class="table is-striped mx-auto">
    <tr>
      <th>Gast</th>
      <th>Spieler</th>
      <th class="has-text-centered hideable-table-col">Pudel</th>
      <th class="has-text-centered hideable-table-col">0.25 €</th>
      <th class="has-text-centered hideable-table-col">0.50 €</th>
      <th class="has-text-centered hideable-table-col">0.75 €</th>
      <th class="has-text-centered hideable-table-col">1.00 €</th>
      <th class="has-text-centered hideable-table-col">1.25 €</th>
      <th class="has-text-centered hideable-table-col">1.50 €</th>
      <th class="has-text-centered hideable-table-col">1.75 €</th>
      <th class="has-text-centered hideable-table-col">5.00 €</th>
      <th class="has-text-centered hideable-table-col">Verspätung</th>
      <th class="has-text-centered hideable-table-col">Früher gehen</th>
      <th class="has-text-centered hideable-table-col">Sonstiges</th>
      <th class="has-text-centered hideable-table-col">Summe Strafen</th>
      <th class="has-text-centered">inkl. Gebühren</th>
    </tr>
    <%= for score <- @scores do %>
      <tr>
        <td class="has-text-centered"><%= player_symbol(score) %></td>
        <td>
          <%= link score.player.name, to: Routes.match_score_path(@conn, :edit, @match, score) %>
          <%= pudel_king_symbol(score, Map.get(@match_stats, :pudel_king_value)) %>
        </td>
        <td class="has-text-right hideable-table-col">
          <%= score.penalty_pudel %>
        </td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_25 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_50 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_75 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_100 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_125 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_150 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_175 %></td>
        <td class="has-text-right hideable-table-col"><%= score.penalty_500 %></td>
        <td class="has-text-right hideable-table-col"><%= score.delay %></td>
        <td class="has-text-right hideable-table-col"><%= score.early_leave %></td>
        <td class="has-text-right hideable-table-col"><%= score.other %></td>
        <td class="has-text-right hideable-table-col"><%= currency_format PegelclubEx.Game.Scores.penalty_sum(score) %></td>
        <td class="has-text-right">
          <%= if @match_stats[:score_totals][score.id] do %>
            <%= currency_format @match_stats[:score_totals][score.id] %>
          <% else %>
            <%= currency_format Map.get(@match_stats, :average) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>